### ISSUE TITLE
Create Request Class

### ISSUE THREAD

**Issue by jennaluz** [Lumenaries/http#3]
Wrap the following functions

- [ ] `int httpd_req_to_sockfd(httpd_req_t* r)`
- [ ] `int httpd_req_recv(httpd_req_t* r, char* buf, size_t buf_len)`
- [ ] `size_t httpd_req_get_hdr_value_len(httpd_req_t* r, const char* field)`
- [x] `esp_err_t httpd_req_get_hdr_value_str(httpd_req_t* r, const char* field, char* value, size_t val_size)`
- [ ] `size_t httpd_req_get_url_query_len(httpd_req_t *r)`
- [x] `esp_err_t httpd_req_get_url_query_str(httpd_req_t *r, char *buf, size_t buf_len)`
- [x] `esp_err_t httpd_req_get_cookie_val(httpd_req_t *req, const char *cookie_name, char *val, size_t *val_size)`
- [x] `esp_err_t httpd_query_key_value(const char *qry, const char *key, char *val, size_t val_size)`

**Comment by loganfin** [comment]
The unchecked functions are either used to assist in calling the checked-functions are are too low-level for the level of abstraction that this library provides.
