### ISSUE TITLE
Create Response Class

### ISSUE THREAD

**Issue by jennaluz** [Lumenaries/http#4]
Wrap the following functions

- [ ] `int httpd_send(httpd_req_t *r, const char *buf, size_t buf_len);`
- [x] `esp_err_t httpd_resp_send(httpd_req_t *r, const char *buf, ssize_t buf_len);`
- [x] `esp_err_t httpd_resp_send_chunk(httpd_req_t *r, const char *buf, ssize_t buf_len);`
- [ ] `static inline esp_err_t httpd_resp_sendstr(httpd_req_t *r, const char *str);`
- [ ] `static inline esp_err_t httpd_resp_sendstr_chunk(httpd_req_t *r, const char *str);`
- [x] `esp_err_t httpd_resp_set_status(httpd_req_t *r, const char *status);`
- [x] `esp_err_t httpd_resp_set_type(httpd_req_t *r, const char *type);`
- [x] `esp_err_t httpd_resp_set_hdr(httpd_req_t *r, const char *field, const char *value);`
- [ ] `esp_err_t httpd_resp_send_err(httpd_req_t *req, httpd_err_code_t error, const char *msg);`

**Comment by loganfin** [comment]
The other functions are either wrappers around the checked-off functions or are unnecessary for now.
